# only needed to make Spack read a custom database generated by spood
# (not needed if you just use external packages defined in packages.yaml)
# only read permissions are needed
upstreams:
  eessi:
    install_tree: ${INSTALL_BASE_PATH}/upstreams/eessi
